Repository nebula-contrib/ngbatis, pull requests merged in 2023-10, with the labels that each got.

#239 test: add test space create nGQL script and instruction
  ngbatis-demo/src/main/resources/docker-compose.yaml
  ngbatis-demo/src/main/resources/testgraph.ngql
Labels: Hacktoberfest, hacktoberfest-accepted

#241 fix:class 'ResultSetUtil.java' parse datetime type error #240
  src/main/java/org/nebula/contrib/ngbatis/utils/ResultSetUtil.java
Labels: Hacktoberfest

#244 Feat: add insertEdgeBatch function #234
  ngbatis-demo/src/test/java/ye/weicheng/ngbatis/demo/NebulaBasicDaoTests.java
  pom.xml
  src/main/java/org/nebula/contrib/ngbatis/models/data/NgTriplet.java
  src/main/java/org/nebula/contrib/ngbatis/proxy/NebulaDaoBasic.java
  src/main/resources/NebulaDaoBasic.xml
Labels: Hacktoberfest, hacktoberfest-accepted

#247 feat: add deleteByIdBatch interface and my information
  ngbatis-demo/src/test/java/ye/weicheng/ngbatis/demo/NebulaBasicDaoTests.java
  src/main/java/org/nebula/contrib/ngbatis/proxy/NebulaDaoBasic.java
  src/main/resources/NebulaDaoBasic.xml
Labels: Hacktoberfest, hacktoberfest-accepted

#250 add EXECUTION-PROCESS.md to docs
  docs/en/md/step-forward-docs/operation-sequence.md
Labels: hacktoberfest-accepted
